export const headphones = [
  {
    id: 1,
    img: "./neoflex/images/Beats Tour.jpg",
    title: "Beats Tour",
    price: 4990,
    rate: 4.4,
    sale: 2491,
    category: "in-ear",
  },
  {
    id: 2,
    img: "./neoflex/images/Beats Mixr.jpg",
    title: "Beats Mixr",
    price: 9900,
    rate: 4.6,
    sale: 0,
    category: "headband",
  },
  {
    id: 3,
    img: "./neoflex/images/PowerBeats 1.jpg",
    title: "PowerBeats 1",
    price: 11000,
    rate: 4.5,
    sale: 0,
    category: "in-ear",
  },
  {
    id: 4,
    img: "./neoflex/images/Beats Tour 2.jpg",
    title: "Beats Tour 2",
    price: 4990,
    rate: 4.0,
    sale: 0,
    category: "in-ear",
  },
  {
    id: 5,
    img: "./neoflex/images/Powerbeats Pro.jpg",
    title: "Powerbeats Pro",
    price: 18990,
    rate: 5.0,
    sale: 0,
    category: "in-ear",
  },
  {
    id: 6,
    img: "./neoflex/images/Beats Solo3 Wireless.jpg",
    title: "Beats Solo 3 Wireless",
    price: 14990,
    rate: 4.9,
    sale: 1990,
    category: "headband",
  },
  {
    id: 7,
    img: "./neoflex/images/PowerBeats 2.jpg",
    title: "PowerBeats 2",
    price: 28000,
    rate: 4.8,
    sale: 5001,
    category: "in-ear",
  },
  {
    id: 8,
    img: "./neoflex/images/urBeats.jpg",
    title: "urBeats",
    price: 3990,
    rate: 4.5,
    sale: 1000,
    category: "in-ear",
  },
  {
    id: 9,
    img: "./neoflex/images/Beats Studio Buds.jpg",
    title: "Beats Studio Buds",
    price: 13990,
    rate: 4.9,
    sale: 0,
    category: "in-ear",
  },
  {
    id: 10,
    img: "./neoflex/images/Beats Fit Pro.jpg",
    title: "Beats Fit Pro",
    price: 19990,
    rate: 4.6,
    sale: 4990,
    category: "in-ear",
  },
  {
    id: 11,
    img: "./neoflex/images/Beats Flex.jpg",
    title: "Beats Flex",
    price: 6490,
    rate: 4.8,
    sale: 0,
    category: "in-ear",
  },
  {
    id: 12,
    img: "./neoflex/images/Beats Solo Pro.jpg",
    title: "Beats Solo Pro",
    price: 14900,
    rate: 4.7,
    sale: 0,
    category: "headband",
  },
];
